name: Deploy Jekyll Site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04-x64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ruby 3.1.4 via ruby-build
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev git
          git clone https://github.com/rbenv/ruby-build.git /tmp/ruby-build
          mkdir -p /opt/hostedtoolcache/Ruby/3.1.4/x64
          PREFIX=/opt/hostedtoolcache/Ruby/3.1.4/x64 /tmp/ruby-build/install.sh
          sudo chmod -R a+rwx /opt/hostedtoolcache/Ruby/3.1.4/x64
          sudo touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ubuntu-24.04-x64
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
